[2023-11-22T12:49:26.206+0545] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summery.download_episodes manual__2023-11-22T07:04:12.308519+00:00 [queued]>
[2023-11-22T12:49:26.212+0545] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summery.download_episodes manual__2023-11-22T07:04:12.308519+00:00 [queued]>
[2023-11-22T12:49:26.212+0545] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T12:49:26.224+0545] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): download_episodes> on 2023-11-22 07:04:12.308519+00:00
[2023-11-22T12:49:26.229+0545] {standard_task_runner.py:57} INFO - Started process 251756 to run task
[2023-11-22T12:49:26.231+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'podcast_summery', 'download_episodes', 'manual__2023-11-22T07:04:12.308519+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summery.py', '--cfg-path', '/tmp/tmprpxvhz89']
[2023-11-22T12:49:26.232+0545] {standard_task_runner.py:85} INFO - Job 175: Subtask download_episodes
[2023-11-22T12:49:26.256+0545] {task_command.py:416} INFO - Running <TaskInstance: podcast_summery.download_episodes manual__2023-11-22T07:04:12.308519+00:00 [running]> on host dwarka.dwarka
[2023-11-22T12:49:26.322+0545] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='podcast_summery' AIRFLOW_CTX_TASK_ID='download_episodes' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T07:04:12.308519+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T07:04:12.308519+00:00'
[2023-11-22T12:49:26.323+0545] {logging_mixin.py:154} INFO - episodes/happy-birthday-chatgpt.mp3
[2023-11-22T12:49:26.324+0545] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/aiflow_project/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ace/airflow/dags/podcast_summery.py", line 64, in download_episodes
    if not os.path.exists("./episodes", mode=777):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: exists() got an unexpected keyword argument 'mode'
[2023-11-22T12:49:26.329+0545] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=podcast_summery, task_id=download_episodes, execution_date=20231122T070412, start_date=20231122T070426, end_date=20231122T070426
[2023-11-22T12:49:26.339+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 175 for task download_episodes (exists() got an unexpected keyword argument 'mode'; 251756)
[2023-11-22T12:49:26.363+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T12:49:26.371+0545] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
